apiVersion: v1
kind: Service
metadata:
  name: {{ include "comdirect-firefly-sync.fullname" . }}
  labels:
    {{- include "comdirect-firefly-sync.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "comdirect-firefly-sync.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
