apiVersion: v1
kind: Service
metadata:
  name: {{ include "comdirect-firefly-sync.fullname" . }}-worker
  labels:
    {{- include "comdirect-firefly-sync.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  selector:
    {{- include "comdirect-firefly-sync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
