image:
  pullPolicy: Always

api:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 512Mi

  env:
    APP_ENV: "production"
    LOG_LEVEL: "INFO"
    SYNC_INTERVAL_MINUTES: "60"
    FIREFLY_BASE_URL: "http://firefly-iii:8080"

ingress:
  enabled: true
  className: traefik
  host: comdirect-sync.max5800.com

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStore:
    name: vault-backend
    kind: ClusterSecretStore
  vaultPath: secret/data/comdirect-firefly-sync
