apiVersion: v1
kind: Service
metadata:
  name: comdirect-api
  namespace: comdirect
spec:
  selector:
    app: comdirect-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
