apiVersion: apps/v1
kind: Deployment
metadata:
  name: comdirect-api
  namespace: comdirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comdirect-api
  template:
    metadata:
      labels:
        app: comdirect-api
    spec:
      containers:
        - name: api
          image: ghcr.io/max5800/comdirect-firefly-sync-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: EXPORTS_DIR
              value: /data/exports
          volumeMounts:
            - name: export-data
              mountPath: /data/exports
              readOnly: true
      volumes:
        - name: export-data
          persistentVolumeClaim:
            claimName: comdirect-export-data
